### ISSUE TITLE
TS #1

### ISSUE THREAD

**Issue by jeonyh0924** [TEAM3x3/backend#106]
- [x] #63 https://docs.python.org/3/library/secrets.html  random-> secret app/goods/models.py 
- [ ] #63 static method optimizing app/goods/model
- [x] #65 pk -> id  serializers
