### ISSUE TITLE
TS #2

### ISSUE THREAD

**Issue by jeonyh0924** [TEAM3x3/backend#107]
- [x] #78 related name 복수로  models 
- [x] #78 testcode  생성 인스턴스 1개일 경우 quantity 제거 
- [x] #78 변수명 유의미 하게 체크
- [x] #78 if sale is not None: 사용하지 말고 if sale: 로 변경 app/goods/view
- [x] #78 choice 필드로 변경 TextChoice 사용 members/serializers
- [x] #78 model property method 들 sum  이용하여 계산 
- [ ] #78 payment = serializers.FloatField(source='total_payment') order/serializers 
- [x] #80 camel -> snake  core.urls & event/serializers mainEvent 
- [x] #82 goods/model Tag unique= True
- [x] #84 goods/serializers.py 이건 직접 체크
- [x] #86 carts/model quantity_of_goods null True 제거
- [x] #86 carts/model transaction.atomic 걸거면 view에서
- [x] #91 테스트 코드 작성시 테스트 대상을 제외한 요청은 http response 사용하지말고 목킹 사용
- [x] #92 goods/views      if len(recommend_items) == 8: 는 8의 의미를 모르니 MAX_RANDOM_ITEM_COUNT = 8 처럼 의미 있는 변수 사용하여 if len(recommend_items) == MAX_RANDOM_ITEM_COUNT:로 가독성을 높인다. 
- [x] #92 members/views.py def get_queryset() 에서 user_pk = self.kwargs.get('user_pk', None) if user_pk:
- [x] #93 order/serializers if qs.count() == 0 하지 말고 if not qs.exitsts()
- [x] #93 https://www.django-rest-framework.org/api-guide/validators/#currentuserdefault perform create 에 유저 주입
- [x] #97 TextChoice
- [x] #97 https://www.django-rest-framework.org/api-guide/validators/#currentuserdefault 뭔지 기억이 안남
- [x] #98 Keyword unique= True, count = models.PositiveField(default=0)

**Comment by jeonyh0924** [comment]
`#78 model property method 들 sum 이용하여 계산` 은 메서드 필드로 만든 값들에 대해서는 Sum() 사용해서 한번에 계산을 할 수 없었다.

**Comment by jeonyh0924** [comment]
121.139.218.165
