### ISSUE TITLE
TS #3

### ISSUE THREAD

**Issue by jeonyh0924** [TEAM3x3/backend#153]
- [x] #103 bulk_delete  -> cart.views.py
- [ ] #105 migrate file >> 개념 미숙, 문서 읽어보기
- [x] #105 order/serialziers.py qs.count() == 0 말고 qs.exists() 사용하기 
- [x] #110  goods_pk = self.kwargs['goods_pk'] 말고 `self.kwargs.get('goods_pk', None)` 으로
- [x] #118 testcode 작성 시 숫자 표시 `1000` -> `1_000`
